// English strings, keyed by the Chinese source text.
export const EN_DICT: Record<string, string> = {
  // 通用 / general
  '设置': 'Settings', '完成': 'Done', '取消': 'Cancel', '打开': 'Open', '导出': 'Export',
  '外观': 'Appearance', '浅色': 'Light', '深色': 'Dark', '浅色模式': 'Light mode', '深色模式': 'Dark mode',
  '音效': 'Sound', '审阅修订时的轻提示音': 'A soft chime while reviewing changes',
  '语言 / Language': 'Language / 语言', '快捷键': 'Keyboard shortcuts',
  '完全离线，文件不会离开这台电脑': 'Fully offline — your files never leave this computer',
  '离线文档比对': 'Offline document compare',
  '收起侧边栏': 'Collapse sidebar', '展开侧边栏': 'Expand sidebar',
  '收起右侧面板': 'Hide side panel', '展开右侧面板': 'Show side panel',
  '新建比较': 'New comparison', '重新比较': 'Compare again', '忽略': 'Dismiss',
  '设置面板': 'Settings',

  // 模式 / modes
  '富文本': 'Rich text', '纯文本': 'Plain text', '修订审阅': 'Review changes', '图像': 'Image',
  'OCR 文本': 'OCR text', '文件详情': 'File details',

  // 首页 / home
  '找出两份文档的每一处不同': 'Find every difference between two documents',
  '准备好了！按「开始比较」吧': 'All set — hit “Compare”',
  'Word、PDF、TXT 任意组合 · 所有处理都在这台电脑上完成，不会上传': 'Any mix of Word, PDF and TXT · everything runs on this computer, nothing is uploaded',
  '原始文档': 'Original', '修改后文档': 'Revised', '原始': 'Original', '修改后': 'Revised',
  '拖入{s}': 'Drop the {s} here', '支持 Word（.docx）、PDF、TXT': 'Word (.docx), PDF and TXT',
  '选择文件': 'Choose file', '粘贴文字': 'Paste text', '更换': 'Replace', '移除': 'Remove',
  '正在读取…': 'Reading…', '{n} 段': '{n} paragraphs', '{n} 页': '{n} pages',
  '没读到文字，可能是扫描件。比较后用「OCR 文本」或「图像」模式。': 'No text found — this may be a scan. After comparing, try OCR text or Image mode.',
  '开始比较': 'Compare', '还差 {n} 个文档': 'Add {n} more file(s)', '也可以直接按': 'or just press',
  '交换左右': 'Swap sides', '交换左右（{k}）': 'Swap sides ({k})', '最近比较': 'Recent comparisons',
  '从列表移除': 'Remove from list', '刚刚': 'just now', '{n} 分钟前': '{n} min ago',
  '{n} 小时前': '{n} h ago', '{n} 天前': '{n} d ago',
  '换一个文件（也可以直接拖进来）': 'Pick another file (or just drop one here)', '已更新': 'updated',
  '找不到「{f}」，它可能被移动或删除了': '“{f}” is missing — it may have been moved or deleted',

  // 弹窗 / modals
  '这个 PDF 有密码': 'This PDF is password protected', '「{f}」受密码保护。': '“{f}” needs a password. ',
  '密码不对，再试一次。': 'Wrong password — try again.', '输入密码': 'Enter password',
  '粘贴{s}的文字': 'Paste the {s} text', '直接粘贴从网页、邮件、聊天软件里复制的内容。': 'Paste anything you copied from a web page, email or chat.',
  '在这里粘贴…（{k}）': 'Paste here… ({k})', '使用这段文字': 'Use this text',
  '粘贴的文字（原始）.txt': 'Pasted text (original).txt', '粘贴的文字（修改后）.txt': 'Pasted text (revised).txt',

  // 快捷键 / shortcuts
  '打开原始文档': 'Open original document', '打开修改后文档': 'Open revised document',
  '切换模式': 'Switch mode', '下一处 / 上一处差异': 'Next / previous difference',
  '（修订审阅）接受 / 拒绝': '(Review) accept / reject', '（修订审阅）撤销当前决定': '(Review) undo decision',
  '交换左右文档': 'Swap the two documents', '（首页）开始比较': '(Home) start comparing',

  // 工具条 / toolbars
  '删除': 'Deleted', '新增': 'Added', '格式': 'Format', '移动': 'Moved', '修改': 'Changed',
  '上一处': 'Previous', '下一处': 'Next', '上一处（K）': 'Previous (K)', '下一处（J）': 'Next (J)',
  '并排': 'Side by side', '合并': 'Unified', '差异': 'Diff', '淡化': 'Fade', '滑块': 'Slider',
  '拖动页面上的分割线来对比': 'Drag the divider on the page to compare', '缩放': 'Zoom',
  '中文 + 英文': 'Chinese + English', '仅中文': 'Chinese only', '仅英文': 'English only',
  '开始识别': 'Run OCR', '重新识别': 'Run OCR again', '取消识别': 'Cancel OCR',
  'Word 最终稿': 'Word — final', '还没处理的修订按“接受”算': 'Undecided changes count as accepted',
  'Word 修订稿': 'Word — tracked', '保留删除线和下划线标记': 'Keeps strikethrough and underline marks',
  '当前修订视图，适合发给别人看': 'The current redline view, good for sharing',
  'Word 文档': 'Word document', '最终稿': 'final', '修订稿': 'tracked', '修订对比': 'redline',
  '已导出：{p}': 'Exported: {p}',
  '红色删除线 = 删除，绿色下划线 = 新增，紫色 = 移动，橙色底线 = 格式变化': 'red strikethrough = deleted, green underline = added, purple = moved, orange underline = formatting',

  // 正文 / body
  '没找到可以比较的文字': 'No text to compare',
  '如果是扫描件，试试「OCR 文本」或「图像」模式。': 'If these are scans, try OCR text or Image mode.',
  '两份文档好像都是空的。': 'Both documents look empty.',
  '没有需要审阅的修订': 'Nothing to review', '两份文档内容一致。': 'The two documents are identical.',
  '正在认真读字…': 'Reading the text…', '先识别，再比较': 'Recognize first, then compare',
  '把两份文档的每一页当成图片来识别文字。适合扫描件、截图型 PDF。': 'Every page is read as an image. Good for scans and screenshot PDFs.',
  '每页大约 3–5 秒，完全离线。': 'About 3–5 s per page, fully offline.',
  '识别失败': 'OCR failed', '已取消识别': 'OCR cancelled', 'OCR 识别完成': 'OCR finished',
  '{a} 与 {b} 已可以比较': '{a} and {b} are ready to compare',
  '正在准备页面…': 'Preparing pages…', '正在加载识别模型…': 'Loading OCR models…',
  '正在准备{s}的第 {i}/{n} 页': 'Preparing page {i}/{n} of the {s}',
  '正在识别{s}：第 {i}/{n} 页': 'Reading the {s}: page {i}/{n}',
  '正在排版文档…': 'Laying out the documents…',
  '正在渲染原始文档第 {i}/{n} 页': 'Rendering page {i}/{n} of the original',
  '正在渲染修改后文档第 {i}/{n} 页': 'Rendering page {i}/{n} of the revised',
  '正在比对第 {i}/{n} 页': 'Comparing page {i}/{n}',
  '页面渲染失败': 'Could not render the pages',
  '第 {n} 页': 'Page {n}', '无差异': 'identical', '差异 {p}% · {n} 处区域': '{p}% different · {n} areas',
  '仅原始文档有此页': 'only in the original', '仅修改后文档有此页': 'only in the revised', '无对应页': 'no matching page',
  '⋯ {n} 个未变化的段落': '⋯ {n} unchanged paragraphs', '⋯ 显示 {n} 行未变化内容': '⋯ show {n} unchanged lines',
  '已移动': 'moved', '从上方移来': 'moved from above', '从下方移来': 'moved from below',
  '样式变化': 'style change', '段落拆分': 'split', '段落合并': 'merged',
  '另一侧没有可对应的内容，已标记所选行': 'Nothing matches on the other side — the selected line is marked',
  '已把两侧对齐到所选行': 'Both sides aligned to the selected line',
  '这一行两侧已经对齐': 'This line is already aligned on both sides',
  '撤销对齐': 'Undo align', '取消标记': 'Clear mark', '图片': 'image',

  // 右侧栏 / side panel
  '差异概览': 'Overview', '复制摘要': 'Copy summary',
  '复制为 Markdown，可粘贴到邮件 / 飞书 / 文档': 'Copies Markdown you can paste into mail or docs',
  '已复制 {n} 处差异的摘要，可以直接粘贴': 'Copied a summary of {n} differences — ready to paste',
  '内容完全一致！': 'Identical!', '格式 / 移动': 'Format / moved',
  '批量处理': 'Bulk actions', '全部接受': 'Accept all', '全部拒绝': 'Reject all', '重置所有决定': 'Reset all decisions',
  '修订列表': 'Change list', '变更列表': 'Change list', '比较设置': 'Compare settings',
  '忽略空白差异': 'Ignore whitespace', '多余空格、换行符不同': 'Extra spaces or different line breaks',
  '忽略全角 / 半角标点': 'Ignore full-width punctuation', '，和 ,　（和 (　视为相同': 'Treats ，（ the same as , (',
  '忽略大小写': 'Ignore case', '检测移动的段落': 'Detect moved paragraphs', '检测格式变化': 'Detect formatting changes',
  'Word 与 PDF 互比时默认关闭': 'Off by default when comparing Word with PDF',
  '加粗、字号、颜色、标题级别': 'Bold, size, color, heading level',
  '只看有变化的段落': 'Only changed paragraphs', '只看有变化的行': 'Only changed lines', '自动换行': 'Wrap lines',
  '比较精度': 'Granularity', '按词': 'Word', '按字符': 'Character',
  '版面对比': 'Layout compare', '页有差异': 'pages differ', '页相同': 'pages identical',
  '每一页都一模一样！': 'Every page matches!', '标出差异区域': 'Outline changed areas',
  '只看有差异的页': 'Only pages with changes', '灵敏度': 'Sensitivity',
  '很高': 'Very high', '标准': 'Standard', '较低': 'Lower', '低': 'Low',
  '页面': 'Pages', '缺页': 'missing', '相同': 'same',
  'Word 和 TXT 会先在本机排成页面再比较，分页可能和 Word 略有不同。': 'Word and TXT files are laid out locally before comparing, so page breaks may differ slightly from Word.',
  '差异地图：点击跳转': 'Difference map — click to jump',

  // 审阅 / review
  '已接受': 'accepted', '已拒绝': 'rejected', '接受': 'Accept', '拒绝': 'Reject', '切换': 'move',
  '已接受，保留新版本': 'Accepted — keeping the new version',
  '已拒绝，恢复原文': 'Rejected — back to the original',
  '第 {i} / {n} 处': 'Change {i} of {n}', '点文中任意一处修订开始审阅': 'Click any marked change to start reviewing',
  '审阅完成！': 'Review complete!', '{n} 处修订全部处理完毕': 'All {n} changes handled',
  '导出 Word 最终稿': 'Export final Word file', '导出 PDF 修订对比': 'Export redline PDF', '回去再看看': 'Back to the document',
  '整段换了位置': 'whole paragraph moved', '整段移动': 'moved', '（段落）': '(paragraph)',
  '「{f}」刚刚在磁盘上被修改了': '“{f}” just changed on disk', '已按最新文件重新比较': 'Recompared with the latest files',

  // 文件详情 / details
  '文件': 'File', '内容统计': 'Content', '文档属性': 'Document properties', '属性': 'Property',
  'Word 文档 (.docx)': 'Word document (.docx)', 'PDF 文档': 'PDF document',
  '（{n} 字节）': ' ({n} bytes)',
  '两个文件的 SHA-256 完全一致，是同一个文件。': 'Both files have the same SHA-256 — they are the same file.',

  // 差异说明 / diff notes
  '加粗': 'bold', '取消加粗': 'not bold', '倾斜': 'italic', '取消倾斜': 'not italic',
  '下划线': 'underline', '取消下划线': 'no underline', '删除线': 'strikethrough', '取消删除线': 'no strikethrough',
  '字号 {a} → {b}': 'size {a} → {b}', '颜色 {a} → {b}': 'color {a} → {b}', '字体 {a} → {b}': 'font {a} → {b}',
  '突出显示 {c}': 'highlight {c}', '取消突出显示': 'no highlight', '默认': 'default',
  '标题 {n}': 'Heading {n}', '列表项': 'List item', '表格行': 'Table row', '正文': 'Body text',
  '段落拆分：{a} 段 → {b} 段': 'Paragraph split: {a} → {b}', '段落合并：{a} 段 → {b} 段': 'Paragraphs merged: {a} → {b}',
  '段落样式：{a} → {b}': 'Paragraph style: {a} → {b}', '对齐：{a} → {b}': 'Alignment: {a} → {b}',
  '居中': 'centered', '右对齐': 'right', '两端对齐': 'justified', '左对齐': 'left',
  '移动到第 {n} 段附近': 'moved near paragraph {n}',

  // 摘要 / markdown summary
  '## 文档差异摘要': '## Document diff summary',
  '- 共 {n} 处：删除 {del}、新增 {ins}、修改 {mod}': '- {n} changes: {del} deleted, {ins} added, {mod} modified',
  '、格式 {n}': ', {n} formatting', '、移动 {n}': ', {n} moved',

  // 错误 / errors
  '「{f}」好像损坏了，或者不是真正的 Word 文档。试试在 Word 里重新另存为 .docx。': '“{f}” looks damaged, or is not really a Word file. Try re-saving it as .docx in Word.',
  '「{f}」无法作为 PDF 读取，文件可能已损坏或只下载了一部分。': '“{f}” could not be read as a PDF — it may be damaged or only partly downloaded.',
  '找不到「{f}」，它可能被移动或删除了。': '“{f}” is missing — it may have been moved or deleted.',
  '没有权限读取「{f}」。': 'No permission to read “{f}”.',
  '暂不支持旧版 .doc 格式。请在 Word 里「另存为」.docx 后再试。': 'The old .doc format is not supported. Save it as .docx in Word first.',
  '还不支持 .{e} 文件。目前支持 Word（.docx）、PDF 和文本（.txt）。': '.{e} files are not supported yet. DocDiff reads Word (.docx), PDF and TXT.',
};
